version: '3.8'

services:
  app:
    image: ghcr.io/adiilpay/prepaidcardsbackend:latest
    container_name: AdiilPayAPI
    environment:
      - DB_URL
      - SECRET_KEY
      - PORT
      - NO_TOKEN_EXPIRATION
      - NODE_ENV
    ports:
      - "3000:3000"
    restart: always