services:
  app:
    image: ghcr.io/adiilpay/prepaidcardsbackend:latest
    container_name: AdiilPayAPI
    environment:
      - DB_URL
      - SECRET_KEY
      - PORT
      - NO_TOKEN_EXPIRATION
      - NODE_ENV
    ports:
      - "${PORT:-20005}:${PORT:-20005}"
    env_file:
      - .env
    restart: always